// <auto-generated />
using System;
using GodGames.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GodGames.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GodGamesDbContext))]
    partial class GodGamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GodId")
                        .HasColumnType("uuid");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PowerUpSlot")
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GodId")
                        .IsUnique();

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.God", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Gods");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("ParsedEffectJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("GodId", "IsApplied");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.NarrativeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TickNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TickNumber");

                    b.ToTable("NarrativeEntries");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.WorldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutcomeModifiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatRequirementsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorldEvents");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.HasOne("GodGames.Domain.Entities.God", "God")
                        .WithOne("Champion")
                        .HasForeignKey("GodGames.Domain.Entities.Champion", "GodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GodGames.Domain.ValueObjects.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ChampionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DEX")
                                .HasColumnType("integer")
                                .HasColumnName("stat_dex");

                            b1.Property<int>("INT")
                                .HasColumnType("integer")
                                .HasColumnName("stat_int");

                            b1.Property<int>("STR")
                                .HasColumnType("integer")
                                .HasColumnName("stat_str");

                            b1.Property<int>("VIT")
                                .HasColumnType("integer")
                                .HasColumnName("stat_vit");

                            b1.Property<int>("WIS")
                                .HasColumnType("integer")
                                .HasColumnName("stat_wis");

                            b1.HasKey("ChampionId");

                            b1.ToTable("Champions");

                            b1.WithOwner()
                                .HasForeignKey("ChampionId");
                        });

                    b.Navigation("God");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("GodGames.Domain.Entities.Champion", "Champion")
                        .WithMany("Interventions")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GodGames.Domain.Entities.God", "God")
                        .WithMany()
                        .HasForeignKey("GodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("God");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.NarrativeEntry", b =>
                {
                    b.HasOne("GodGames.Domain.Entities.Champion", "Champion")
                        .WithMany("NarrativeEntries")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("NarrativeEntries");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.God", b =>
                {
                    b.Navigation("Champion");
                });
#pragma warning restore 612, 618
        }
    }
}
