// <auto-generated />
using System;
using GodGames.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GodGames.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GodGamesDbContext))]
    partial class GodGamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveDebuff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActiveDebuffTicksRemaining")
                        .HasColumnType("integer");

                    b.Property<string>("Biome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CombatWins")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveCursedTicks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentRegionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DivineFavourCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExploredRegionIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GodId")
                        .HasColumnType("uuid");

                    b.Property<int>("HP")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHP")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PersonalityTrait")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PowerUpSlot")
                        .HasColumnType("text");

                    b.Property<int>("PowerUpTicksRemaining")
                        .HasColumnType("integer");

                    b.Property<int>("TicksSurvivedStreak")
                        .HasColumnType("integer");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GodId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("ParsedEffectJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.HasIndex("GodId", "IsApplied");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.NarrativeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChampionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TickNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId", "TickNumber");

                    b.ToTable("NarrativeEntries");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.WorldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutcomeModifiersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatRequirementsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorldEvents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Biome = "Safe",
                            Description = "A bustling market where merchants hawk their wares and travelers share tales.",
                            Name = "Village Market",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Biome = "Safe",
                            Description = "A well-worn trail through a peaceful woodland.",
                            Name = "Forest Path",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Biome = "Safe",
                            Description = "A warm inn offering rest and rumours.",
                            Name = "Roadside Inn",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Biome = "Safe",
                            Description = "A sacred road walked by devout pilgrims seeking distant shrines.",
                            Name = "Pilgrim's Road",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Biome = "Safe",
                            Description = "A trading caravan offering exotic goods from distant lands.",
                            Name = "Merchant Caravan",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Biome = "Safe",
                            Description = "Crumbling ruins of a forgotten civilisation, now largely explored and safe.",
                            Name = "Ancient Ruins",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"WIS\": 8}"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Biome = "Safe",
                            Description = "A mystical spring with restorative waters blessed by forgotten gods.",
                            Name = "Healing Spring",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Biome = "Normal",
                            Description = "A gang of goblins leaps from the treeline to harass travellers.",
                            Name = "Goblin Ambush",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"STR\": 12}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Biome = "Normal",
                            Description = "A fortified camp of outlaws blocking the road ahead.",
                            Name = "Bandit Camp",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"DEX\": 12}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Biome = "Normal",
                            Description = "An ancient wood where malevolent spirits lead travellers astray.",
                            Name = "Dark Forest",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"WIS\": 12}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Biome = "Normal",
                            Description = "An old burial chamber whose undead residents resent intruders.",
                            Name = "Haunted Crypt",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"INT\": 12}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Biome = "Normal",
                            Description = "A treacherous mountain crossing battered by harsh winds.",
                            Name = "Mountain Pass",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"VIT\": 12}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Biome = "Normal",
                            Description = "A swollen river where the current threatens to sweep travellers away.",
                            Name = "River Crossing",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"STR\": 10}"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Biome = "Normal",
                            Description = "A hulking troll demands payment — or combat — to cross its bridge.",
                            Name = "Troll Bridge",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"STR\": 14}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Biome = "Dangerous",
                            Description = "The lair of an ancient dragon hoarding centuries of plunder.",
                            Name = "Dragon's Lair",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"STR\": 18}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Biome = "Dangerous",
                            Description = "A dark spire where a lich commands an army of the undead.",
                            Name = "Necromancer's Tower",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"INT\": 18}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Biome = "Dangerous",
                            Description = "The shadow compound of a deadly guild who silence loose ends.",
                            Name = "Assassin's Guild",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"DEX\": 18}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Biome = "Dangerous",
                            Description = "An ancient demon of immense power seeking a soul to devour.",
                            Name = "Elder Demon",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"VIT\": 18}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Biome = "Dangerous",
                            Description = "A fortress built by giants and still guarded by their descendants.",
                            Name = "Titan's Keep",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"STR\": 15, \"VIT\": 15, \"WIS\": 15}"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            Biome = "Dangerous",
                            Description = "A tear in reality that draws the unwary into the consuming void.",
                            Name = "Void Rift",
                            OutcomeModifiersJson = "{}",
                            StatRequirementsJson = "{\"WIS\": 18}"
                        });
                });

            modelBuilder.Entity("GodGames.Domain.Entities.WorldRegion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActiveEventTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Biome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DifficultyRating")
                        .HasColumnType("integer");

                    b.Property<int>("MapX")
                        .HasColumnType("integer");

                    b.Property<int>("MapY")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevelRequired")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WorldRegions");

                    b.HasData(
                        new
                        {
                            Id = "whispering-fields",
                            ActiveEventTypes = "Exploration, Rest, Trade",
                            Biome = "Safe",
                            Description = "Gentle grasslands where young champions first find their footing.",
                            DifficultyRating = 1,
                            MapX = 80,
                            MapY = 480,
                            MinLevelRequired = 1,
                            Name = "Whispering Fields"
                        },
                        new
                        {
                            Id = "greenwatch-village",
                            ActiveEventTypes = "Trade, Rest, Healing",
                            Biome = "Safe",
                            Description = "A welcoming village with markets, healers, and rumours of glory.",
                            DifficultyRating = 2,
                            MapX = 200,
                            MapY = 510,
                            MinLevelRequired = 1,
                            Name = "Greenwatch Village"
                        },
                        new
                        {
                            Id = "sunken-grove",
                            ActiveEventTypes = "Exploration, Combat, Loot",
                            Biome = "Safe",
                            Description = "Ancient ruins half-buried in woodland, with minor creatures lurking.",
                            DifficultyRating = 3,
                            MapX = 330,
                            MapY = 460,
                            MinLevelRequired = 2,
                            Name = "Sunken Grove"
                        },
                        new
                        {
                            Id = "ironveil-pass",
                            ActiveEventTypes = "Combat, Ambush, Trade",
                            Biome = "Normal",
                            Description = "A treacherous mountain pass frequented by bandits and desperate travellers.",
                            DifficultyRating = 4,
                            MapX = 70,
                            MapY = 300,
                            MinLevelRequired = 5,
                            Name = "Ironveil Pass"
                        },
                        new
                        {
                            Id = "ashwood-crossing",
                            ActiveEventTypes = "Combat, Exploration, Curse",
                            Biome = "Normal",
                            Description = "A river crossing through a charred forest, haunted by restless spirits.",
                            DifficultyRating = 5,
                            MapX = 200,
                            MapY = 280,
                            MinLevelRequired = 5,
                            Name = "Ashwood Crossing"
                        },
                        new
                        {
                            Id = "the-bleached-crypt",
                            ActiveEventTypes = "Combat, Loot, Undead",
                            Biome = "Normal",
                            Description = "An ancient necropolis filled with undead guardians and forgotten treasure.",
                            DifficultyRating = 6,
                            MapX = 330,
                            MapY = 320,
                            MinLevelRequired = 7,
                            Name = "The Bleached Crypt"
                        },
                        new
                        {
                            Id = "dragonspine-ridge",
                            ActiveEventTypes = "Combat, Dragon, Fire",
                            Biome = "Dangerous",
                            Description = "Volcanic ridgelines where dragons nest and the air tastes of sulphur.",
                            DifficultyRating = 8,
                            MapX = 80,
                            MapY = 120,
                            MinLevelRequired = 10,
                            Name = "Dragonspine Ridge"
                        },
                        new
                        {
                            Id = "void-threshold",
                            ActiveEventTypes = "Combat, Demon, Void",
                            Biome = "Dangerous",
                            Description = "A rift in reality where demon lords breach the mortal plane.",
                            DifficultyRating = 9,
                            MapX = 200,
                            MapY = 80,
                            MinLevelRequired = 10,
                            Name = "Void Threshold"
                        },
                        new
                        {
                            Id = "the-obsidian-keep",
                            ActiveEventTypes = "Combat, Boss, Necromancy",
                            Biome = "Dangerous",
                            Description = "Fortress of the Necromancer-King — only the mightiest dare enter.",
                            DifficultyRating = 10,
                            MapX = 330,
                            MapY = 110,
                            MinLevelRequired = 12,
                            Name = "The Obsidian Keep"
                        });
                });

            modelBuilder.Entity("GodGames.Infrastructure.Identity.GodUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("PatronTitle")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.OwnsOne("GodGames.Domain.ValueObjects.Stats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ChampionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DEX")
                                .HasColumnType("integer")
                                .HasColumnName("stat_dex");

                            b1.Property<int>("INT")
                                .HasColumnType("integer")
                                .HasColumnName("stat_int");

                            b1.Property<int>("STR")
                                .HasColumnType("integer")
                                .HasColumnName("stat_str");

                            b1.Property<int>("VIT")
                                .HasColumnType("integer")
                                .HasColumnName("stat_vit");

                            b1.Property<int>("WIS")
                                .HasColumnType("integer")
                                .HasColumnName("stat_wis");

                            b1.HasKey("ChampionId");

                            b1.ToTable("Champions");

                            b1.WithOwner()
                                .HasForeignKey("ChampionId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("GodGames.Domain.Entities.Champion", "Champion")
                        .WithMany("Interventions")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("GodGames.Domain.Entities.NarrativeEntry", b =>
                {
                    b.HasOne("GodGames.Domain.Entities.Champion", "Champion")
                        .WithMany("NarrativeEntries")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GodGames.Infrastructure.Identity.GodUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GodGames.Infrastructure.Identity.GodUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GodGames.Infrastructure.Identity.GodUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GodGames.Infrastructure.Identity.GodUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GodGames.Domain.Entities.Champion", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("NarrativeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
